name: Sync Labels

on:
  push:
    branches: [main]
    paths: [.github/labels.json]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Sync labels
        uses: EndBug/label-sync@7753e99e1e64188c24d7deede343c5a63e7c0d39 # v2.3.3
        with:
          config-file: .github/labels.json
          delete-other-labels: false
          dry-run: false
